name: ToolSentinelEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - imutils=0.5.4
  - face_recognition=1.3.0
  - transitions=0.9.0
  - pip
  - pip:
    - pyttsx3 == 2.90
    - opencv-python == 4.9.0
    - SpeechRecognition == 3.10.1
    - pyaudio == 0.2.14
    - vosk == 0.3.45

